// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerInput {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(float, tag = "2")]
    pub throttle: f32,
    #[prost(float, tag = "3")]
    pub yaw: f32,
    #[prost(float, tag = "4")]
    pub pitch: f32,
    #[prost(float, tag = "5")]
    pub roll: f32,
    #[prost(bool, tag = "6")]
    pub shoot: bool,
    #[prost(int32, tag = "7")]
    pub activate_module: i32,
    #[prost(int64, tag = "8")]
    pub timestamp: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShipState {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(message, optional, tag = "2")]
    pub position: ::core::option::Option<super::common::Vector3>,
    #[prost(message, optional, tag = "3")]
    pub velocity: ::core::option::Option<super::common::Vector3>,
    #[prost(message, optional, tag = "4")]
    pub rotation: ::core::option::Option<super::common::Quaternion>,
    #[prost(float, tag = "5")]
    pub shield_hp: f32,
    #[prost(float, tag = "6")]
    pub armor_hp: f32,
    #[prost(float, tag = "7")]
    pub energy: f32,
    #[prost(float, tag = "8")]
    pub heat_level: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DamageEvent {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(message, optional, tag = "2")]
    pub source: ::core::option::Option<super::common::PlayerId>,
    #[prost(message, optional, tag = "3")]
    pub target: ::core::option::Option<super::common::PlayerId>,
    #[prost(string, tag = "4")]
    pub damage_type: ::prost::alloc::string::String,
    #[prost(float, tag = "5")]
    pub raw_amount: f32,
    #[prost(float, tag = "6")]
    pub mitigated_amount: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModuleActivation {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(string, tag = "2")]
    pub module_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub activation_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub target_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WeaponOverheat {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(string, tag = "2")]
    pub weapon_id: ::prost::alloc::string::String,
    #[prost(float, tag = "3")]
    pub heat_percentage: f32,
    #[prost(bool, tag = "4")]
    pub overheated: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MissileLaunch {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(string, tag = "2")]
    pub missile_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub launcher_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub target: ::core::option::Option<super::common::PlayerId>,
    #[prost(message, optional, tag = "5")]
    pub position: ::core::option::Option<super::common::Vector3>,
    #[prost(message, optional, tag = "6")]
    pub velocity: ::core::option::Option<super::common::Vector3>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameStateSnapshot {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(uint32, tag = "2")]
    pub tick_number: u32,
    #[prost(message, repeated, tag = "3")]
    pub players: ::prost::alloc::vec::Vec<ShipState>,
    #[prost(message, repeated, tag = "4")]
    pub damage_events: ::prost::alloc::vec::Vec<DamageEvent>,
    #[prost(message, repeated, tag = "5")]
    pub missile_states: ::prost::alloc::vec::Vec<MissileLaunch>,
}
