version: "3.9"

services:
  postgres-dev:
    image: docker.io/postgres:16-alpine
    container_name: stargem-postgres-dev
    environment:
      POSTGRES_USER: stargem
      POSTGRES_PASSWORD: stargem
      POSTGRES_DB: stargem
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stargem -d stargem"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
