id = "550e8400-e29b-41d4-a716-446655440009"
size = "Interceptor"
role = "Ecm"
price = 34000
base_shield = 100.0
base_armor = 50.0
base_energy = 250.0
base_speed = 125.0
base_agility = 0.85
shields_count = 1
armors_count = 0
capacitors_count = 2
motors_count = 0
computers_count = 1
